Input_File_Name=S1_side.pov
Output_to_File=True
Output_File_Type=N
Output_Alpha=off
; if you adjust Height, and width, you must preserve the ratio
; Width / Height = 1.182130
Width=1200
Height=1015.1170591108594
Antialias=True
Antialias_Threshold=0.1
Display=False
Display_Gamma=2.2
Pause_When_Done=True
Verbose=False
